project:
  type: book

book:
  title: "Personal Notes: Statistical Rethinking (2nd ed)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon.ico"

  chapters:
    - index.qmd
    - 01-golem-of-prague.qmd
    - 02-small-and-large-worlds.qmd
    - 03-sampling-the-imaginary.qmd
    - 04-geocentric-models.qmd
    - 05-many-variables.qmd
    - 95-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: glossary.css
    number-sections: true
    toc-depth: 5
    toc-expand: 2
    code-fold: false
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

execute:
    freeze: auto

language:
   crossref-fig-title: "Picture"
   crossref-prp-title: "Callout"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Resource"         # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Wach out!"    # orange
   callout-important-title: "Procedure"  # red
   callout-caution-title: "TODO"         # yellow
